# Install Terraform with Ansible playbook
- hosts: "{{group}}"
  become: yes
  gather_facts: false

  vars_prompt:
    - name: group 
      prompt: Enter target group
      private: no

  tasks:
    - name: Update apt package list on Ubuntu
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Install gnupg & software-properties-common
      apt:
        name: 
          - gnupg 
          - software-properties-common
        state: present
        force_apt_get: yes

    - name: Install wget 
      apt:
        name: wget
        state: present

    - name: Download & add  HashiCorp GPG key 
      shell: |
        wget -O- https://apt.releases.hashicorp.com/gpg | \
        gpg --dearmor | \
        sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null

    - name: Verify GPG key's Fingerprint 
      shell: |
        gpg --no-default-keyring \
        --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg \
        --fingerprint

    - name: Add the official HashiCorp repository to your system
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
        https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
        sudo tee /etc/apt/sources.list.d/hashicorp.list

    - name: Download the package information from HashiCorp.
      apt:
        update_cache: yes

    - name: Install Terraform from the new repository.
      apt:
        name: terraform
        state: present
        force_apt_get: yes

    - name: Verifiy Terraform Installation.
      shell: terraform --version
      register: terraform_version

    - name: Display Terraform Version
      debug:
        var: terraform_version.stdout

    - name: Create Terraform Project directory
      file:
        path: ~/terraform-vpc  
        state: directory

    - name: Upload Terraform file into Terraform Project directory
      copy:
        src: aws-vpc.tf
        dest: ~/terraform-vpc/aws-vpc.tf

    - name: Change to Terraform project directory
      shell: cd ~/terraform-vpc
      args:
        chdir: ~/terraform-vpc


    - name: Initialized Terraform directory
      shell: terraform init
      args:
        chdir: ~/terraform-vpc
      register: terraform_init

    - name: Display Terraform Init Status
      debug:
        var: terraform_init.stdout


    - name: Format Terraform files
      shell: terraform fmt
      args:
        chdir: ~/terraform-vpc
      register: terraform_fmt

    - name: Display Terraform Format Status
      debug:
        var: terraform_fmt.stdout


    - name: Validate Terraform configuration
      shell: terraform validate
      args:
        chdir: ~/terraform-vpc
      register: terraform_validate

    - name: Display Terraform Validation Status
      debug:
        var: terraform_validate.stdout